
name: 部署文档

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
          version: 8

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run build
          > docs/.vuepress/dist/.nojekyll

      # 新增：打包构建产物
      - name: 打包文档构建产物
        run: |
          cd docs/.vuepress/dist
          tar -czf ../../../samwaf-docs-build.tar.gz .
          cd ../../../
          zip -r samwaf-docs-build.zip docs/.vuepress/dist/

      # 新增：上传构建产物作为artifact
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: samwaf-docs-build
          path: |
            samwaf-docs-build.tar.gz
            samwaf-docs-build.zip
          retention-days: 30

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: gh-pages
          folder: docs/.vuepress/dist
